### ISSUE TITLE
https://hook.io/Marak/image/rotate is not working

### ISSUE THREAD

**Issue by shufengh** [bigcompany/hook.io#154]
Tried the pipe example and found the follow:

```
Error communicating with worker http://worker3:10000/marak/image/rotate

The streaming connection errored in recieving data.

Please copy and paste this entire error message to Support.

Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Thanks! It's a great idea like IFTTT for devs

**Comment by Marak** [comment]
Hi!

We've got an issue right now with graphic magick `gm` module not working. #146 

I thought I had removed the links to the image examples on the homepage!

I'll see if I can get `gm` working again.
