### ISSUE TITLE
Error stacktrace creating a new hook

### ISSUE THREAD

**Issue by palmerabollo** [bigcompany/hook.io#164]
Hi. I am getting the following stacktrace when I try to create a new hook in the website.

```
TypeError: Cannot read property 'resource' of undefined
   at view [as presenter] (/root/hook.io/view/layout.js:3:19)
   at View.present (/root/hook.io/node_modules/view/lib/View.js:314:39)
   at module.exports (/root/hook.io/node_modules/view/lib/layout.js:36:31)
   at View.present (/root/hook.io/node_modules/view/lib/View.js:276:14)
   at bodyParsed (/root/hook.io/view/new.js:150:42)
   at urlencodedParser (/root/hook.io/node_modules/body-parser/lib/types/urlencoded.js:88:40)
   at /root/hook.io/node_modules/body-parser/index.js:111:7
   at jsonParser (/root/hook.io/node_modules/body-parser/lib/types/json.js:100:40)
   at bodyParser (/root/hook.io/node_modules/body-parser/index.js:109:5)
   at view [as presenter] (/root/hook.io/view/new.js:28:15)
   at /root/hook.io/node_modules/view/lib/View.js:285:43
   at /root/hook.io/node_modules/view/lib/layout.js:39:16
   at /root/hook.io/node_modules/view/lib/View.js:319:14
   at view [as presenter] (/root/hook.io/view/layout.js:30:3)
   at View.present (/root/hook.io/node_modules/view/lib/View.js:314:39)
   at module.exports (/root/hook.io/node_modules/view/lib/layout.js:36:31) 
```

Thanks for your help.

**Comment by Marak** [comment]
Sorry about that. Should be resolved now.

We had a bug sneak in this mornign with the latest version of `view@0.8.3`. I rolled the dependency back to the previous version.

Small issues like this shouldn't happen in anymore once we put our integration tests online. see: https://github.com/bigcompany/hook.io-test

Thank you!
