### ISSUE TITLE
Error: ENOENT, no such file or directory '/src/node_modules/hook.io-vfs/config/.ssh/id_rsa' after docker-compose up

### ISSUE THREAD

**Issue by jmatsushita** [bigcompany/hook.io#229]
```
$ docker-compose up
Creating hookio_redis_1
Creating hookio_couch_1
Creating hookio_setup_1
Creating hookio_worker0_1
Creating hookio_hookio_1
Creating hookio_install_default_hooks_1
Attaching to hookio_redis_1, hookio_couch_1, hookio_setup_1, hookio_worker0_1, hookio_hookio_1, hookio_install_default_hooks_1
redis_1                 | 1:C 26 Apr 10:00:13.553 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                 |                 _._                                                  
redis_1                 |            _.-``__ ''-._                                             
redis_1                 |       _.-``    `.  `_.  ''-._           Redis 3.0.7 (00000000/0) 64 bit
redis_1                 |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1                 |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1                 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1                 |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1                 |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1                 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1                 |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1                 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1                 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1                 |  |    `-._`-._        _.-'_.-'    |                                  
redis_1                 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1                 |       `-._    `-.__.-'    _.-'                                       
redis_1                 |           `-._        _.-'                                           
redis_1                 |               `-.__.-'                                               
redis_1                 | 
redis_1                 | 1:M 26 Apr 10:00:13.559 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                 | 1:M 26 Apr 10:00:13.559 # Server started, Redis version 3.0.7
redis_1                 | 1:M 26 Apr 10:00:13.560 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                 | 1:M 26 Apr 10:00:13.560 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                 | 1:M 26 Apr 10:00:13.560 * The server is now ready to accept connections on port 6379
setup_1                 |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
setup_1                 |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
couch_1                 | Apache CouchDB 1.6.1 (LogLevel=info) is starting.
hookio_setup_1 exited with code 7
couch_1                 | Apache CouchDB has started. Time to relax.
couch_1                 | [info] [<0.32.0>] Apache CouchDB has started on http://0.0.0.0:5984/
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
worker0_1               | Warning: Redis server does not require a password, but a password was supplied.
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
worker0_1               | changed root to "/Users/chroot" and user to "worker"
worker0_1               | worker started 4:0.0.0.0:10000
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
hookio_1                | Warning: Redis server does not require a password, but a password was supplied.
couch_1                 | [info] [<0.121.0>] 172.17.0.4 - - PUT /hook 201
hookio_1                | !!Created new couchdb hook
couch_1                 | [info] [<0.120.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                 | [info] [<0.119.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                 | [info] [<0.118.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                 | [info] [<0.117.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                 | [info] [<0.116.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                 | [info] [<0.170.0>] 172.17.0.4 - - PUT /hook/_design/nano 201
couch_1                 | [info] [<0.171.0>] 172.17.0.4 - - PUT /hook/_design/nano 409
couch_1                 | [info] [<0.172.0>] 172.17.0.4 - - PUT /hook/_design/nano 409
couch_1                 | [info] [<0.173.0>] 172.17.0.4 - - PUT /hook/_design/nano 409
couch_1                 | [info] [<0.174.0>] 172.17.0.4 - - PUT /hook/_design/nano 409
hookio_1                | Using custom domains middleware [ 'hookio', '0.0.0.0', 'localhost', 'hook.io', 'www.hook.io' ]
hookio_1                | fs.js:565
hookio_1                | fs.write = function(fd, buffer, offset, length, position, callback) {
hookio_1                |                                                  ^
hookio_1                | Error: ENOENT, no such file or directory '/src/node_modules/hook.io-vfs/config/.ssh/id_rsa'
hookio_1                |     at Error (native)
hookio_1                |     at Object.fs.openSync (fs.js:500:18)
hookio_1                |     at Object.fs.readFileSync (fs.js:352:15)
hookio_1                |     at Object.<anonymous> (/src/node_modules/hook.io-vfs/config/index.js:39:31)
hookio_1                |     at Module._compile (module.js:460:26)
hookio_1                |     at Object.Module._extensions..js (module.js:478:10)
hookio_1                |     at Module.load (module.js:355:32)
hookio_1                |     at Function.Module._load (module.js:310:12)
hookio_1                |     at Module.require (module.js:365:17)
hookio_1                |     at require (module.js:384:17)
hookio_1                |     at Object.<anonymous> (/src/node_modules/hook.io-vfs/lib/server.js:5:14)
hookio_1                |     at Module._compile (module.js:460:26)
hookio_1                |     at Object.Module._extensions..js (module.js:478:10)
hookio_1                |     at Module.load (module.js:355:32)
hookio_1                |     at Function.Module._load (module.js:310:12)
hookio_1                |     at Module.require (module.js:365:17)
hookio_1                |     at require (module.js:384:17)
hookio_hookio_1 exited with code 1
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN
couch_1                 | [info] [<0.176.0>] 172.17.0.6 - - GET /hook/_design/nano 200
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN
couch_1                 | [info] [<0.188.0>] Opening index for db: hook idx: _design/nano sig: "175a31325ef88dc6b12bf58c6d220a19"
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
install_default_hooks_1 | Error: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN
install_default_hooks_1 | Error: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | Error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | Error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
couch_1                 | [info] [<0.106.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
install_default_hooks_1 | warning: bypassing role access
couch_1                 | [info] [<0.107.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | created view
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
couch_1                 | [info] [<0.108.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
install_default_hooks_1 | warning: bypassing role access
couch_1                 | [info] [<0.109.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | created spellcheck
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
couch_1                 | [info] [<0.110.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
install_default_hooks_1 | warning: bypassing role access
couch_1                 | [info] [<0.111.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | created markdown
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
couch_1                 | [info] [<0.112.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
install_default_hooks_1 | warning: bypassing role access
couch_1                 | [info] [<0.113.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | created isthewebsitedown
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
couch_1                 | [info] [<0.115.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
install_default_hooks_1 | warning: bypassing role access
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
couch_1                 | [info] [<0.114.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | created geoip
install_default_hooks_1 | Error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index update finished for db: hook idx: _design/nano
couch_1                 | [info] [<0.158.0>] 172.17.0.6 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
install_default_hooks_1 | warning: bypassing role access
couch_1                 | [info] [<0.183.0>] 172.17.0.6 - - POST /hook 201
install_default_hooks_1 | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1 | created gateway-tcl
couch_1                 | [info] [<0.193.0>] Starting index update for db: hook idx: _design/nano
couch_1                 | [info] [<0.193.0>] Index upda
```

**Comment by Marak** [comment]
Possibly resolved with https://github.com/bigcompany/hook.io-vfs/commit/08f02ccdb2405f6b545fb508971a1a099fb0f778

**Comment by Marak** [comment]
Error is `Error: ENOENT, no such file or directory '/src/node_modules/hook.io-vfs/config/.ssh/id_rsa'`

**Comment by Marak** [comment]
The `vfs` stuff is all brand new. Not even in production yet.

**Comment by jmatsushita** [comment]
Ah ha! Ok no worries. Will rebuild and let you know how it goes. I guess I could deactivate the `vfs` stuff too. Is it as simple as removing it from the package.json?

**Comment by Marak** [comment]
I really can't speak for the state of `master`. Maybe?

`vfs` is required in other pages.

I'd suggest not trying to deactivate anything.

**Comment by jmatsushita** [comment]
Ok sounds good. Hope you don't mind me posting issues as I go along.

**Comment by Marak** [comment]
It's okay, I'm glad to assist.

If you are motivated to get the stack working, you can. Everything should be there.

**Comment by jmatsushita** [comment]
Rebuilding worked. Closing.
