### ISSUE TITLE
TypeError: Cannot read property '192.168.99.100' of undefined

### ISSUE THREAD

**Issue by jmatsushita** [bigcompany/hook.io#230]
When running the `curl http://192.168.99.100/_admin?baseUrl=set` as advised [in the README](https://github.com/bigcompany/hook.io#configure-the-local-running-hookio-instance) I get the following error:

```
couch_1                 | [info] [<0.446.0>] 172.17.0.4 - - POST /hook/_design/nano/_view/by_model?include_docs=true 200
hookio_1                | TypeError: Cannot read property '192.168.99.100' of undefined
hookio_1                |     at viewMiddle (/src/node_modules/resource-http/lib/listen.js:194:33)
hookio_1                |     at Layer.handle [as handle_request] (/src/node_modules/resource-http/node_modules/express/lib/router/layer.js:95:5)
hookio_1                |     at trim_prefix (/src/node_modules/resource-http/node_modules/express/lib/router/index.js:312:13)
hookio_1                |     at /src/node_modules/resource-http/node_modules/express/lib/router/index.js:280:7
hookio_1                |     at Function.process_params (/src/node_modules/resource-http/node_modules/express/lib/router/index.js:330:12)
hookio_1                |     at next (/src/node_modules/resource-http/node_modules/express/lib/router/index.js:271:10)
hookio_1                |     at EventEmitter.<anonymous> (/src/node_modules/resource-http/lib/middlewares/customDomains.js:33:17)
hookio_1                |     at /src/node_modules/resource/lib/method.js:159:29
hookio_1                |     at afterHooks (/src/node_modules/resource/lib/method.js:193:11)
hookio_1                |     at callbackWrap (/src/node_modules/resource/lib/method.js:155:18)
hookio_1                |     at /src/node_modules/resource/lib/datasource/find.js:36:7
hookio_1                |     at /src/node_modules/resource/node_modules/jugglingdb/lib/model.js:450:13
hookio_1                |     at /src/node_modules/jugglingdb-nano/lib/nano.js:335:16
hookio_1                |     at Request._callback (/src/node_modules/jugglingdb-nano/node_modules/nano/nano.js:288:11)
hookio_1                |     at Request.self.callback (/src/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:129:22)
hookio_1                |     at Request.emit (events.js:110:17)

```

**Comment by Marak** [comment]
Yeah, that is a simple reference error in `master` version of https://github.com/bigcompany/http

Sorry, can't push the fix as I have uncommitted changes locally. All of this stuff is due to changes from today.

Like I said before, `master` isn't currently stable, and won't be until the next release.

**Comment by jmatsushita** [comment]
Ok cool. I'll check back later today.

**Comment by jmatsushita** [comment]
Hi @Marak seems like there's a lot of new code since 17 days ago. How can I follow whether we're close to the next release or not?
