### ISSUE TITLE
How to update hook source using the API

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#240]
I've found #221, but instruction there doesn't works:
```console
C:\src\tests>cat hookupdate.js
var sdk = require("hook.io-sdk");

var client = sdk.createClient({});

client.hook.update('testeb43df31_2329bb48hook', { "source": 'print(globals())', "language": "python" }, function (err, res) {
  console.log(err, res)
});
C:\src\tests>node hookupdate.js
{ Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at TLSSocket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } undefined
```
I've tried to do this with curl with same results:
```console
$ curl -i -H "hookio-private-key: $hook_private_key" -H 'accept: application/json' --data 'source=print(globals())&owner=pythonsdktest&name=testeb43df31_2329bb48hook&language=python&save=save' 'https://hook.io/admin'
curl: (52) Empty reply from server
$ curl -i -H "hookio-private-key: $hook_private_key" -H 'accept: application/json' -H 'content-type: application/json' --data-raw '{"source":"print(globals())","owner":"pythonsdktest","name":"testeb43df31_2329bb48hook","language":"python","save":"save"}' 'https://hook.io/admin'
curl: (52) Empty reply from server
```
```

**Comment by sumbudy** [comment]
Any patch for this issue?

**Comment by Marak** [comment]
Checking today.

Will have an update shortly.

**Comment by Marak** [comment]
This should be hot-patched on production, was a one-line fix.

Commits coming.

**Comment by WilliamFink** [comment]
Where's my Bitcoins Marak Squires? William Fink (516) 287-5737 william.fink@yahoo.com http://www.facebook.com/william.fink 

    On Thursday, August 25, 2016 3:23 PM, Marak <notifications@github.com> wrote:
 

 This should be hot-patched on production, was a one-line fix.Commits coming.—
