### ISSUE TITLE
docker setup on local is not working.

### ISSUE THREAD

**Issue by muthusk** [bigcompany/hook.io#252]
After couchdb and redis have come up docker-compose up throws the follow error. 
please suggest a solution.

hookio_1                 | /src/bin/server:2
hookio_1                 | server.start({}, function(err, app){
hookio_1                 |        ^
hookio_1                 | TypeError: undefined is not a function
hookio_1                 |     at Object.<anonymous> (/src/bin/server:2:8)
hookio_1                 |     at Module._compile (module.js:460:26)
hookio_1                 |     at Object.Module._extensions..js (module.js:478:10)
hookio_1                 |     at Module.load (module.js:355:32)
hookio_1                 |     at Function.Module._load (module.js:310:12)
hookio_1                 |     at Function.Module.runMain (module.js:501:10)
hookio_1                 |     at startup (node.js:129:16)
hookio_1                 |     at node.js:814:3
hookio_hookio_1 exited with code 1
worker0_1                | /src/node_modules/oys/config/production/index.js:24
worker0_1                |   username: "admin",
worker0_1                |   ^^^^^^^^
worker0_1                | SyntaxError: Unexpected identifier
worker0_1                |     at exports.runInThisContext (vm.js:73:16)
worker0_1                |     at Module._compile (module.js:443:25)
worker0_1                |     at Object.Module._extensions..js (module.js:478:10)
worker0_1                |     at Module.load (module.js:355:32)
worker0_1                |     at Function.Module._load (module.js:310:12)
worker0_1                |     at Module.require (module.js:365:17)
worker0_1                |     at require (module.js:384:17)
worker0_1                |     at Object.<anonymous> (/src/node_modules/oys/config/index.js:3:18)
worker0_1                |     at Module._compile (module.js:460:26)
worker0_1                |     at Object.Module._extensions..js (module.js:478:10)
install_default_hooks_1  | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1  | Error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1  | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1  | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1  | Error Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
install_default_hooks_1  | Error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis
couch_1                  | [error] [<0.153.0>] Could not open file /usr/local/var/lib/couchdb/hook.couch: no such file or directory
couch_1                  | [info] [<0.104.0>] 172.17.0.4 - - GET /hook/_design/nano 404
couch_1                  | [error] [<0.158.0>] Could not open file /usr/local/var/lib/couchdb/hook.couch: no such file or directory
couch_1                  | [info] [<0.105.0>] 172.17.0.4 - - PUT /hook/_design/nano 404
couch_1                  | [error] [<0.162.0>] Could not open file /usr/local/var/lib/couchdb/hook.couch: no such file or directory
couch_1                  | [info] [<0.106.0>] 172.17.0.4 - - POST /hook/_design/nano/_view/by_model?include_docs=true 404
install_default_hooks_1  | /src/scripts/install/add-default-hooks.js:41
install_default_hooks_1  |       throw err;
install_default_hooks_1  |             ^
install_default_hooks_1  | Error: no_db_file
install_default_hooks_1  |     at Request._callback (/src/node_modules/jugglingdb-nano/node_modules/nano/nano.js:304:39)
install_default_hooks_1  |     at Request.self.callback (/src/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:129:22)
install_default_hooks_1  |     at Request.emit (events.js:110:17)
install_default_hooks_1  |     at Request.<anonymous> (/src/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:873:14)
install_default_hooks_1  |     at Request.emit (events.js:129:20)
install_default_hooks_1  |     at IncomingMessage.<anonymous> (/src/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:824:12)
install_default_hooks_1  |     at IncomingMessage.emit (events.js:129:20)
install_default_hooks_1  |     at _stream_readable.js:908:16
install_default_hooks_1  |     at process._tickCallback (node.js:355:11)
hookio_worker0_1 exited with code 1
hookio_install_default_hooks_1 exited with code 1

**Comment by jnpr-muthusk** [comment]
Was able to find the issue on 'oys' npm module, missing a ","  after port number. few more issues to fix...

**Comment by muthusk** [comment]
"oys" npm module code is having a missing comma after port number in the file  /src/node_modules/oys/config/production/index.js 
Few more things to fix..

**Comment by labajo** [comment]
I get the same error.

**Comment by muthusk** [comment]
@labajo Did you try with the developer branch or master branch? It may be worth checking the dev branch with docker setup, I havent tried it yet though. @Marak Can you provide some pointers here?

**Comment by labajo** [comment]
I tried it on master branch.

**Comment by muthusk** [comment]
@labajo Let me know if you try dev branch and if it works. What alternatives are you looking otherwise?

**Comment by labajo** [comment]
@muthusk the latest commit on dev branch was performed one year ago or more. I think we have to check the commits in master branch or check our docker system. I don't know exactly.

**Comment by Marak** [comment]
Still working on getting the docker working for the whole platform. Should have `master` working soon.

If you need to run local microservice functions you might want to check-out https://github.com/stackvana/stack

**Comment by levivoelz** [comment]
Hi @Marak, I'm getting a similar error when running `docker-compose up` from the master branch. Is there a way to get this going by changing some Docker configs? Or, would it be better to install everything directly on my host machine?
