### ISSUE TITLE
error happened in your connection

### ISSUE THREAD

**Issue by sumbudy** [bigcompany/hook.io#253]
Error: getaddrinfo ENOENT
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

**Comment by Marak** [comment]
@sumbudy -

Could you elaborate what happened here?

I just got an alert in our error logs. 

Were you working on a new service or was this an issue with an existing service?
