### ISSUE TITLE
(2018-12-21) 500 Internal Server Error

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#316]
```
Error: Could not connect to session server. Is redis running at: redis:6379?
    at /root/aug-hook/node_modules/resource-http/lib/listen.js:180:21
    at Layer.handle [as handle_request] (/root/aug-hook/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/aug-hook/node_modules/express/lib/router/index.js:317:13)
    at /root/aug-hook/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/aug-hook/node_modules/express/lib/router/index.js:335:12)
    at next (/root/aug-hook/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/root/aug-hook/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at SessionStrategy.authenticate (/root/aug-hook/node_modules/passport/lib/strategies/session.js:67:10)
    at attempt (/root/aug-hook/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/root/aug-hook/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/root/aug-hook/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/aug-hook/node_modules/express/lib/router/index.js:317:13)
    at /root/aug-hook/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/aug-hook/node_modules/express/lib/router/index.js:335:12)
    at next (/root/aug-hook/node_modules/express/lib/router/index.js:275:10)
    at initialize (/root/aug-hook/node_modules/passport/lib/middleware/initialize.js:62:5)
```

**Comment by jayl22** [comment]
I have the same problem...can't access the website because of that:/
