### ISSUE TITLE
Problems with npm installation

### ISSUE THREAD

**Issue by JamesB-Kent** [bigcompany/hook.io#83]
Hi, I'm having some problems getting the npm hook.io installation to work on my local computer. These are the messages from "> npm install -g hook.io", and "> hook":

```
-----> npm install hook.io -g
npm WARN engine npm@1.1.71: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.2","npm":"2.7.4"})

> weak@0.1.5 preinstall /home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/weak
> node build.js

child_process: customFds option is deprecated, use stdio instead.
/bin/sh: 1: node-waf: not found
/bin/sh: 1: node-waf: not found
npm WARN excluding symbolic link lib/socket.io-client.js -> io.js
-
> ws@0.4.32 install /home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/socket.io-client/node_modules/ws/build'
/home/james/.nvm/versions/node/v0.12.2/bin/hook -> /home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/bin/hookio
/home/james/.nvm/versions/node/v0.12.2/bin/hookio -> /home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/bin/hookio
hook.io@0.8.11 /home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io
├── eventemitter2@0.4.14
├── jsonify@0.0.0
├── semver@1.0.14
├── colors@0.6.2
├── pkginfo@0.2.3
├── async@0.1.22
├── mkdirp@0.2.2
├── portfinder@0.2.1 (mkdirp@0.0.7)
├── lazy@1.0.11
├── prompt@0.1.12
├── traverse@0.6.6
├── weak@0.1.5
├── optimist@0.2.8 (wordwrap@0.0.3)
├── nconf@0.3.1 (ini@1.3.4)
├── ecstatic@0.1.7 (ent@0.0.7, mime@1.2.5)
├── union@0.3.8 (qs@0.5.6)
├── socket.io@0.9.6 (policyfile@0.0.4, redis@0.6.7)
├── winston@0.5.10 (stack-trace@0.0.9, eyes@0.1.8, loggly@0.3.11)
├── npm@1.1.71
└── socket.io-client@0.9.6 (xmlhttprequest@1.2.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
```
```
-----> hook
/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/weak/lib/bindings.js:19
  throw new Error('Could not load any possibilities')
        ^
Error: Could not load any possibilities
    at requireTry (/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/weak/lib/bindings.js:19:9)
    at Object.<anonymous> (/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/node_modules/weak/lib/weak.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/james/.nvm/versions/node/v0.12.2/lib/node_modules/hook.io/vendor/dnode/index.js:7:12)
    at Module._compile (module.js:460:26)
```

I'm not really sure whether this is a mistake at my end. This is using NVM for the node installation, on Ubuntu 14.04. I tried patching weak to the latest version, the error with weak then disappeared, and another error with nconf appeared, I patched that to the latest version, and then I got a direct error in the hook.io package.

Any idea what's going on?

**Comment by Marak** [comment]
To install hook.io you'll want to clone the repo from Github and build from
source. The package on npm is a few years old and is not the same project.

The `hook.io` npm package will eventually be updated to contain the hook.io
CLI tool / API Client. The server component needs to be cloned from this
repo.

**Comment by JamesB-Kent** [comment]
Ah, I see, thanks for the reply.
